// Mock data for Evaly clone

export const categories = [
  { name: 'Electronics & Audio', slug: 'electronics-audio', icon: 'Headphones' },
  { name: 'Appliances', slug: 'appliances', icon: 'Refrigerator' },
  { name: 'Baby & Kids', slug: 'baby-kids', icon: 'Baby' },
  { name: 'Fashion', slug: 'fashion', icon: 'Shirt' },
  { name: 'Health & Wellness', slug: 'health-wellness', icon: 'HeartPulse' },
  { name: 'Books & Stationery', slug: 'books-stationery', icon: 'BookOpen' },
  { name: 'Beauty & Personal Care', slug: 'beauty-personal-care', icon: 'Sparkles' },
  { name: 'Home & Living', slug: 'home-living', icon: 'Sofa' },
  { name: 'Toys & Games', slug: 'toys-games', icon: 'Gamepad2' },
  { name: 'Garden & Outdoor', slug: 'garden-outdoor', icon: 'Trees' },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', icon: 'Dumbbell' },
  { name: 'Groceries & Food', slug: 'groceries-food', icon: 'ShoppingBasket' },
  { name: 'Mobiles & Tablets', slug: 'mobiles-tablets', icon: 'Smartphone' },
  { name: 'Automotive & Bikes', slug: 'automotive-bikes', icon: 'Car' },
  { name: 'Bags & Luggage', slug: 'bags-luggage', icon: 'Backpack' },
  { name: 'Watches', slug: 'watches', icon: 'Watch' },
];

export const products = [
  {
    id: 'p1',
    slug: 'philips-hp8108-hair-dryer',
    name: 'Philips HP8108 Hair Dryer',
    price: 1899,
    oldPrice: 2500,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=80',
    store: 'ct tech',
    verified: true,
    category: 'beauty-personal-care',
    isNew: true,
    freeDelivery: true,
    rating: 4.5,
    sold: 1240,
    description: 'Compact 1200W hair dryer with ThermoProtect, two heat & speed settings and cool shot for everyday styling.',
  },
  {
    id: 'p2',
    slug: 'evaly-classic-sneaker',
    name: 'Evaly Classic Running Sneaker',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    store: 'Evaly Official Store',
    verified: true,
    category: 'fashion',
    isNew: true,
    freeDelivery: true,
    rating: 4.3,
    sold: 890,
    description: 'Lightweight everyday sneaker with breathable mesh upper and cushioned EVA midsole for all-day comfort.',
  },
  {
    id: 'p3',
    slug: 'bajaj-2-8l-electric-kettle',
    name: 'Bajaj 2.8 L Electric Kettle',
    price: 1490,
    oldPrice: 1850,
    discount: 19,
    image: 'https://images.unsplash.com/photo-1643114786355-ff9e52736eab?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHwxfHxlbGVjdHJpYyUyMGtldHRsZXxlbnwwfHx8fDE3ODEyNjc0OTZ8MA&ixlib=rb-4.1.0&q=85',
    store: 'ct tech',
    verified: true,
    category: 'appliances',
    isNew: true,
    freeDelivery: true,
    rating: 4.4,
    sold: 540,
    description: 'Stainless steel 2.8L kettle with auto shut-off, boil-dry protection and concealed heating element.',
  },
  {
    id: 'p4',
    slug: 'getwell-nebulizer-machine',
    name: 'Getwell Nebulizer Machine',
    price: 2450,
    oldPrice: 3000,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800&q=80',
    store: 'ct tech',
    verified: true,
    category: 'health-wellness',
    isNew: true,
    freeDelivery: true,
    rating: 4.7,
    sold: 320,
    description: 'Compressor nebulizer for adults & kids — quiet operation, fine mist, includes mask & mouthpiece.',
  },
  {
    id: 'p5',
    slug: 'omron-bp-monitor-hem-7121j',
    name: 'Omron Blood Pressure Monitor (HEM-7121J)',
    price: 3649,
    oldPrice: 5200,
    discount: 30,
    image: 'https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?w=800&q=80',
    store: 'ct tech',
    verified: true,
    category: 'health-wellness',
    isNew: true,
    freeDelivery: true,
    rating: 4.8,
    sold: 1820,
    description: 'Clinically validated upper arm BP monitor — Intellisense tech, irregular heartbeat detection, 1-user memory.',
  },
  {
    id: 'p6',
    slug: 'jy-super-2218-rechargeable-fan',
    name: 'JY Super 2218 Rechargeable Fan',
    price: 1100,
    oldPrice: 1450,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1565374395542-0ce18882c857?w=800&q=80',
    store: 'ct tech',
    verified: true,
    category: 'appliances',
    isNew: true,
    freeDelivery: true,
    rating: 4.2,
    sold: 670,
    description: 'Foldable USB rechargeable table fan with 3-speed settings and built-in LED light — up to 8 hrs battery.',
  },
  {
    id: 'p7',
    slug: 'iphone-15-pro-256gb',
    name: 'Apple iPhone 15 Pro 256GB — Natural Titanium',
    price: 165000,
    oldPrice: 178000,
    discount: 7,
    image: 'https://images.unsplash.com/photo-1634403665481-74948d815f03?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA3MDB8MHwxfHNlYXJjaHwyfHxpUGhvbmUlMjBzbWFydHBob25lfGVufDB8fHx8MTc4MTI2NzQ5Nnww&ixlib=rb-4.1.0&q=85',
    store: 'DNA CELL',
    verified: true,
    category: 'mobiles-tablets',
    isNew: true,
    freeDelivery: true,
    rating: 4.9,
    sold: 240,
    description: 'A17 Pro chip, 48MP main camera, USB-C, titanium design — global ROM with 1-year official warranty.',
  },
  {
    id: 'p8',
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra 12/512GB',
    price: 154999,
    oldPrice: 169999,
    discount: 9,
    image: 'https://images.unsplash.com/photo-1707438095940-1eee18e85400?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxNzV8MHwxfHNlYXJjaHwxfHxTYW1zdW5nJTIwR2FsYXh5JTIwcGhvbmV8ZW58MHx8fHwxNzgxMjY3NDk2fDA&ixlib=rb-4.1.0&q=85',
    store: 'NM Technology & Engineering',
    verified: true,
    category: 'mobiles-tablets',
    isNew: true,
    freeDelivery: true,
    rating: 4.8,
    sold: 410,
    description: '6.8" QHD+ AMOLED, Snapdragon 8 Gen 3 for Galaxy, 200MP camera, S-Pen — Galaxy AI built in.',
  },
  {
    id: 'p9',
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    price: 32500,
    oldPrice: 38000,
    discount: 14,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80',
    store: 'Gadget Ministry',
    verified: true,
    category: 'electronics-audio',
    isNew: true,
    freeDelivery: true,
    rating: 4.9,
    sold: 980,
    description: 'Industry-leading ANC, 30hr battery, multipoint Bluetooth, hi-res audio with LDAC.',
  },
  {
    id: 'p10',
    slug: 'atomberg-studio-nexus-fan',
    name: 'Atomberg Studio Nexus 1400mm BLDC Smart Ceiling Fan',
    price: 12150,
    image: 'https://images.unsplash.com/photo-1609519479841-5fd3b2884e17?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NDh8MHwxfHNlYXJjaHwxfHxjZWlsaW5nJTIwZmFufGVufDB8fHx8MTc4MTI2NzQ5Nnww&ixlib=rb-4.1.0&q=85',
    store: 'The wafi mart',
    verified: true,
    category: 'appliances',
    isNew: true,
    freeDelivery: true,
    rating: 4.6,
    sold: 210,
    description: 'IoT-enabled BLDC ceiling fan with remote — 60% energy saving, sleep/timer modes, app control.',
  },
  {
    id: 'p11',
    slug: 'baseus-cleaning-brush',
    name: 'Baseus Multifunctional Cleaning Brush',
    price: 600,
    oldPrice: 1050,
    discount: 43,
    image: 'https://images.unsplash.com/photo-1583947581924-860bda3ab5b0?w=800&q=80',
    store: 'Gadget Ministry',
    verified: true,
    category: 'home-living',
    isNew: true,
    freeDelivery: true,
    rating: 4.4,
    sold: 1530,
    description: '7-in-1 cleaning brush for laptops, keyboards, earphones — soft bristles, fine tips, retractable design.',
  },
  {
    id: 'p12',
    slug: 'naviforce-9038-watch',
    name: 'Naviforce NF9038 Dual Display Sports Watch',
    price: 2890,
    oldPrice: 3500,
    discount: 17,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80',
    store: 'Naviforce & Olives Authorised',
    verified: true,
    category: 'watches',
    isNew: true,
    freeDelivery: true,
    rating: 4.5,
    sold: 760,
    description: 'Analog-digital dual display, 30M water resistant, stainless steel case, chronograph & alarm.',
  },
  {
    id: 'p13',
    slug: 'philips-air-fryer-hd9252',
    name: 'Philips Essential Air Fryer HD9252',
    price: 13990,
    oldPrice: 16500,
    discount: 15,
    image: 'https://images.unsplash.com/photo-1648405568037-5b07cf2eb274?w=800&q=80',
    store: 'ct tech',
    verified: true,
    category: 'appliances',
    isNew: true,
    freeDelivery: true,
    rating: 4.7,
    sold: 540,
    description: 'Rapid Air technology — fry, bake, grill & roast with up to 90% less fat. 4.1L capacity.',
  },
  {
    id: 'p14',
    slug: 'nike-air-max-90',
    name: 'Nike Air Max 90 — White / Black',
    price: 11500,
    oldPrice: 14000,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    store: 'abir mart',
    verified: true,
    category: 'fashion',
    isNew: true,
    freeDelivery: true,
    rating: 4.6,
    sold: 320,
    description: 'Iconic Air Max 90 with visible heel Air unit, leather & textile upper, rubber waffle outsole.',
  },
  {
    id: 'p15',
    slug: 'lego-classic-creative-box',
    name: 'LEGO Classic Creative Bricks Box (484 pcs)',
    price: 3450,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&q=80',
    store: 'JK SHOP',
    verified: true,
    category: 'toys-games',
    isNew: true,
    freeDelivery: true,
    rating: 4.9,
    sold: 140,
    description: '484 LEGO bricks in 35 colours for endless creative play. Includes window & door elements.',
  },
  {
    id: 'p16',
    slug: 'maybelline-fit-me-foundation',
    name: 'Maybelline Fit Me Matte + Poreless Foundation',
    price: 950,
    oldPrice: 1200,
    discount: 21,
    image: 'https://images.unsplash.com/photo-1557205465-f3762edea6d3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxODF8MHwxfHNlYXJjaHwzfHxtYWtldXAlMjBmb3VuZGF0aW9ufGVufDB8fHx8MTc4MTI2NzUwNHww&ixlib=rb-4.1.0&q=85',
    store: 'Evaly Official Store',
    verified: true,
    category: 'beauty-personal-care',
    isNew: true,
    freeDelivery: true,
    rating: 4.5,
    sold: 2210,
    description: 'Mattifying liquid foundation for normal-to-oily skin. Blurs pores, controls shine, natural finish.',
  },
];

export const stores = [
  { name: 'DNA CELL', slug: 'dna-cell', verified: true, products: 312 },
  { name: 'NM Technology & Engineering', slug: 'nm-tech', verified: true, products: 198 },
  { name: 'JK SHOP', slug: 'jk-shop', verified: true, products: 156 },
  { name: 'Gadget Ministry', slug: 'gadget-ministry', verified: true, products: 421 },
  { name: 'Naviforce & Olives', slug: 'naviforce', verified: true, products: 89 },
  { name: 'ct tech', slug: 'ct-tech', verified: true, products: 540 },
  { name: 'The wafi mart', slug: 'wafi-mart', verified: true, products: 234 },
  { name: 'abir mart', slug: 'abir-mart', verified: true, products: 178 },
];

export const brands = [
  { name: 'HAVELLS', slug: 'havells', logo: 'https://uploads.evaly.com.bd/brands/a5216d13f79e06adcb807c0be624633d.png' },
  { name: 'NOKIA', slug: 'nokia', logo: 'https://uploads.evaly.com.bd/brands/6488901cf171ff455af6bc15f0158aee.png' },
  { name: 'RED TAPE', slug: 'red-tape', logo: 'https://uploads.evaly.com.bd/brands/7aba76d1384c8e32a8d0433ffb15d23c.png' },
  { name: 'VISION', slug: 'vision', logo: 'https://uploads.evaly.com.bd/brands/314dbcb49e78f77c9d361381ed0509e6.png' },
  { name: 'PHILIPS', slug: 'philips', logo: null },
  { name: 'SAMSUNG', slug: 'samsung', logo: null },
  { name: 'APPLE', slug: 'apple', logo: null },
  { name: 'BAJAJ', slug: 'bajaj', logo: null },
];

export const promoCards = [
  {
    title: 'Fashion deals',
    href: '/category/fashion',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&q=80',
    overlay: 'from-rose-900/40 to-rose-500/10',
  },
  {
    title: 'Electronics deals',
    href: '/category/electronics-audio',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&q=80',
    overlay: 'from-indigo-900/40 to-indigo-500/10',
  },
];

export const trendingTabs = ['Mobiles & Tablets', 'Electronics', 'Beauty', 'Fashion', 'Home & Appliances'];

export const formatBDT = (n) => {
  if (n === undefined || n === null) return '';
  return n.toLocaleString('en-IN');
};
